#!/bin/bash
#modificar el script creado en el inciso anterior para que los números sean recibidos
#como parámetros. El script debe controlar que los dos parámetros sean enviados.
if [ $# -gt 0 ]; then
	let suma=$(($1+$2))
	echo "La suma es: $suma"

	let resta=$(($1-$2))
	echo "La resta es: $resta"

	if [ $1 -gt $2 ]; then
	        echo "EL mayor es: $1"
	else
	        echo "El mayor es: $2"
	fi
else
	echo "No se ingresaron parametros"
fi
